import apache_log_parser 
import induce
import collections
import random
random.seed(0)


def test_apachelogparse1():
    log_lines = '''
127.0.0.1 <<6113>> [16/Aug/2013:15:45:34 +0000] 1966093us "GET / HTTP/1.1" 200 3478  "https://example.com/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.18)" - -
'''[1:-1]
    grammar = '''
$START ::= $TEST_APACHELOGPARSE1:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.PID$ESCAPE:PATTERN$FORMAT_TIME:TIME_RECEIVED $TEST_APACHELOGPARSE1:PARSE_@.TIME_US$ESCAPE:PATTERN$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.STATUS $TEST_APACHELOGPARSE1:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"$PARSEUSERAGENT:USER_AGENT_STRING$ESCAPE:PATTERN- -
$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE ::= $MATCH:STRING
$PARSEUSERAGENT:USER_AGENT_STRING ::= $PARSEDEVICE:USER_AGENT_STRING
$FORMAT_TIME:TIME_RECEIVED ::= [16/Aug/$USERAGENTPARSER.V1_REPLACEMENT:15:45:34 $APACHETIME:TZ_STRING]
$ESCAPE:PATTERN ::=   "
	|  <<
	| " 
	| >> 
	| us "
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_REFERER ::= $<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER
$TEST_APACHELOGPARSE1:PARSE_@.RESPONSE_BYTES_CLF ::= $<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF
$TEST_APACHELOGPARSE1:PARSE_@.REMOTE_HOST ::= $<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST
$TEST_APACHELOGPARSE1:PARSE_@.TIME_US ::= $<LAMBDA>:MATCHED_STRINGS.TIME_US
$TEST_APACHELOGPARSE1:PARSE_@.STATUS ::= $<LAMBDA>:MATCHED_STRINGS.STATUS
$TEST_APACHELOGPARSE1:PARSE_@.PID ::= $<LAMBDA>:MATCHED_STRINGS.PID
$PARSEDEVICE:USER_AGENT_STRING ::= Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-US; rv:1.9.2.18)
$APACHETIME:TZ_STRING ::= $__INIT__:STRING
$MATCH:STRING ::= $EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE
$<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER ::= $PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER
$<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF ::= $PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF
$<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST ::= $PARSE:<LAMBDA>_@.REMOTE_HOST
$<LAMBDA>:MATCHED_STRINGS.TIME_US ::= $PARSE:<LAMBDA>_@.TIME_US
$<LAMBDA>:MATCHED_STRINGS.STATUS ::= $PARSE:<LAMBDA>_@.STATUS
$USERAGENTPARSER.V1_REPLACEMENT ::= $OSPARSER.OS_V1_REPLACEMENT
$<LAMBDA>:MATCHED_STRINGS.PID ::= $PARSE:<LAMBDA>_@.PID
$PARSE_OPERATING_SYSTEM:FAMILY ::= $__NEW__:FAMILY
$__INIT__:STRING ::= +$FIXEDOFFSET._FIXEDOFFSET__NAME
$EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_FIRST_LINE
$PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER ::= $PARSE:RESULTS.REQUEST_HEADER_REFERER
$PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF ::= $PARSE:RESULTS.RESPONSE_BYTES_CLF
$PARSE:<LAMBDA>_@.REMOTE_HOST ::= $PARSE:RESULTS.REMOTE_HOST
$OSPARSER.OS_V1_REPLACEMENT ::= 2013
$PARSE:<LAMBDA>_@.TIME_US ::= $PARSE:RESULTS.TIME_US
$PARSE:<LAMBDA>_@.STATUS ::= $PARSE:RESULTS.STATUS
$PARSE:<LAMBDA>_@.PID ::= $PARSE:RESULTS.PID
$__NEW__:FAMILY ::= $PARSEOS:OS
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE
$PARSE:RESULTS.REQUEST_HEADER_REFERER ::= $PARSE:VALUES.REQUEST_HEADER_REFERER
$PARSE:RESULTS.RESPONSE_BYTES_CLF ::= $PARSE:VALUES.RESPONSE_BYTES_CLF
$FIXEDOFFSET._FIXEDOFFSET__NAME ::= 0000
$PARSE:RESULTS.REMOTE_HOST ::= $PARSE:VALUES.REMOTE_HOST
$PARSE:RESULTS.TIME_US ::= $PARSE:VALUES.TIME_US
$PARSE:RESULTS.STATUS ::= $PARSE:VALUES.STATUS
$PARSE:RESULTS.PID ::= $PARSE:VALUES.PID
$PARSEOS:OS ::= $PARSE:OS
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD / HTTP/$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER
$PARSE:VALUES.REQUEST_HEADER_REFERER ::= https://example.com/
$PARSE:VALUES.RESPONSE_BYTES_CLF ::= 3478
$PARSE:VALUES.REMOTE_HOST ::= 127.0.0.1
$PARSE:VALUES.TIME_US ::= 1966093
$PARSE:VALUES.STATUS ::= 200
$PARSE:VALUES.PID ::= 6113
$PARSE:OS ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HTTP_VER
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_METHOD
$PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HTTP_VER ::= $PARSE:RESULTS.REQUEST_HTTP_VER
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_METHOD ::= $PARSE:RESULTS.REQUEST_METHOD
$PARSE:RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:RESULTS.REQUEST_HTTP_VER ::= $PARSE:VALUES.REQUEST_HTTP_VER
$PARSE:RESULTS.REQUEST_METHOD ::= $PARSE:VALUES.REQUEST_METHOD
$PARSE:VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSEOS_@.FAMILY
$PARSE:VALUES.REQUEST_HTTP_VER ::= 1.1
$PARSE:VALUES.REQUEST_METHOD ::= GET
$PARSE:PARSEOS_@.FAMILY ::= $__INIT__:PARSE_@.OS.FAMILY
$__INIT__:PARSE_@.OS.FAMILY ::= $__INIT__:UA_DICT.OS.FAMILY
$__INIT__:UA_DICT.OS.FAMILY ::= $PARSE:V.OS.FAMILY
$PARSE:V.OS.FAMILY ::= Linux
'''[1:-1]
    result = []
    for log in log_lines.split('\n'):
        if log.strip() == '': continue
        with induce.Tracer(log, result) as t:
            line_parser = apache_log_parser.make_parser("%h <<%P>> %t %Dus \"%r\" %>s %b  \"%{Referer}i\" \"%{User-Agent}i\" %l %u")
            log_line_data = line_parser(log)
    with induce.grammar() as g:
        for jframe in result:
                g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

def test_apachelogparse2():
    log_lines = '''
127.0.0.1 <<6113>> [16/Aug/2013:15:45:34 +0000] 1966093us "GET / HTTP/1.1" 200 3478  "https://example.com/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.18)" - -
127.0.0.1 <<6113>> [16/Aug/2013:15:45:39 +0000] 1966093us "GET /test HTTP/1.0" 200 3000  "https://myexample.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
10.1.1.1 <<6113>> [16/Aug/2013:15:35:39 +0000] 1966093us "GET /test1 HTTP/1.0" 200 3000  "https://newwebsite.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
10.1.1.1 <<6113>> [16/Aug/2013:15:45:39 +0000] 1966093us "GET /test2 HTTP/1.1" 200 3000  "https://myexample.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
'''[1:-1]
    grammar = '''
$START ::= $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN$FORMAT_TIME:TIME_RECEIVED $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"$PARSEUSERAGENT:USER_AGENT_STRING$ESCAPE:PATTERN- -
	| $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN$FORMAT_TIME:TIME_RECEIVED $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)$ESCAPE:PATTERN- -
	| $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN$FORMAT_TIME:TIME_RECEIVED $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-US; rv:1.9.2.18)$ESCAPE:PATTERN- -
	| 10.$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER.1$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN$FORMAT_TIME:TIME_RECEIVED $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)$ESCAPE:PATTERN- -
$EXTRA_REQUEST_FROM_FIRST_LINE:FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD $EXTRA_REQUEST_FROM_FIRST_LINE:URL HTTP/$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER
	| $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD $EXTRA_REQUEST_FROM_FIRST_LINE:URL HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER
	| $MATCH:STRING
$PARSE_OPERATING_SYSTEM:FAMILY ::= $__NEW__:FAMILY
$FORMAT_TIME:TIME_RECEIVED ::= [16/Aug/$USERAGENTPARSER.V1_REPLACEMENT:15:45:39 $APACHETIME:TZ_STRING]
	| [16/Aug/2013:15:35:39 $APACHETIME:TZ_STRING]
	| [16/Aug/2013:15:45:34 $APACHETIME:TZ_STRING]
	| [16/Aug/2013:15:45:39 $APACHETIME:TZ_STRING]
$ESCAPE:PATTERN ::=   "
	|  <<
	| " 
	| >> 
	| us "
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER ::= $<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER
$TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF ::= $<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF
$TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST ::= $<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST
$TEST_APACHELOGPARSE2:PARSE_@.TIME_US ::= $<LAMBDA>:MATCHED_STRINGS.TIME_US
$TEST_APACHELOGPARSE2:PARSE_@.STATUS ::= $<LAMBDA>:MATCHED_STRINGS.STATUS
$TEST_APACHELOGPARSE2:PARSE_@.PID ::= $<LAMBDA>:MATCHED_STRINGS.PID
$APACHETIME:TZ_STRING ::= $__INIT__:STRING
$__NEW__:FAMILY ::= $PARSEOS:OS
	| $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$MATCH:STRING ::= $EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE
$<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER ::= $PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER
$<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF ::= $PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF
$<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST ::= $PARSE:<LAMBDA>_@.REMOTE_HOST
$<LAMBDA>:MATCHED_STRINGS.TIME_US ::= $PARSE:<LAMBDA>_@.TIME_US
$<LAMBDA>:MATCHED_STRINGS.STATUS ::= $PARSE:<LAMBDA>_@.STATUS
$<LAMBDA>:MATCHED_STRINGS.PID ::= $PARSE:<LAMBDA>_@.PID
$__INIT__:STRING ::= +$FIXEDOFFSET._FIXEDOFFSET__NAME
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_FIRST_LINE
$PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER ::= $PARSE:RESULTS.REQUEST_HEADER_REFERER
$PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF ::= $PARSE:RESULTS.RESPONSE_BYTES_CLF
$PARSE:<LAMBDA>_@.REMOTE_HOST ::= $PARSE:RESULTS.REMOTE_HOST
$PARSE:<LAMBDA>_@.TIME_US ::= $PARSE:RESULTS.TIME_US
$PARSE:<LAMBDA>_@.STATUS ::= $PARSE:RESULTS.STATUS
$PARSE:<LAMBDA>_@.PID ::= $PARSE:RESULTS.PID
$PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE
$PARSE:RESULTS.REQUEST_HEADER_REFERER ::= $PARSE:VALUES.REQUEST_HEADER_REFERER
$PARSE:RESULTS.RESPONSE_BYTES_CLF ::= $PARSE:VALUES.RESPONSE_BYTES_CLF
$FIXEDOFFSET._FIXEDOFFSET__NAME ::= 0000
$PARSE:RESULTS.REMOTE_HOST ::= $PARSE:VALUES.REMOTE_HOST
$PARSE:RESULTS.TIME_US ::= $PARSE:VALUES.TIME_US
$PARSE:RESULTS.STATUS ::= $PARSE:VALUES.STATUS
$PARSE:RESULTS.PID ::= $PARSE:VALUES.PID
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD / HTTP/$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER
$PARSE:RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:VALUES.REQUEST_HEADER_REFERER ::= https://example.com/
	| https://myexample.org/
	| https://newwebsite.org/
$PARSE:VALUES.RESPONSE_BYTES_CLF ::= 3000
	| 3478
$PARSE:VALUES.REMOTE_HOST ::= 10.1.1.1
	| 127.0.0.1
$PARSE:VALUES.TIME_US ::= 1966093
$PARSE:VALUES.STATUS ::= 200
$PARSE:VALUES.PID ::= 6113
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_HTTP_VER ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_METHOD ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD
$PARSE:VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSEOS_@.FAMILY
	| $__INIT__:PARSE_@.OS.FAMILY
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HTTP_VER
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_METHOD
$__INIT__:PARSE_@.OS.FAMILY ::= $__INIT__:UA_DICT.OS.FAMILY
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HTTP_VER ::= $PARSE:RESULTS.REQUEST_HTTP_VER
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_METHOD ::= $PARSE:RESULTS.REQUEST_METHOD
$__INIT__:UA_DICT.OS.FAMILY ::= $PARSE:CACHED.OS.FAMILY
	| $PARSE:V.OS.FAMILY
$PARSE:RESULTS.REQUEST_HTTP_VER ::= $PARSE:VALUES.REQUEST_HTTP_VER
$PARSE:RESULTS.REQUEST_METHOD ::= $PARSE:VALUES.REQUEST_METHOD
$PARSE:CACHED.OS.FAMILY ::= FreeBSD
	| Linux
$PARSE:VALUES.REQUEST_HTTP_VER ::= 1.0
	| 1.1
$PARSE:VALUES.REQUEST_METHOD ::= GET
$PARSEUSERAGENT:USER_AGENT_STRING ::= $PARSEDEVICE:USER_AGENT_STRING
$EXTRA_REQUEST_FROM_FIRST_LINE:URL ::= $__NEW__:PATH
$PARSEDEVICE:USER_AGENT_STRING ::= Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)
$USERAGENTPARSER.V1_REPLACEMENT ::= $OSPARSER.OS_V1_REPLACEMENT
$__NEW__:PATH ::= $URLPARSE:URL
$OSPARSER.OS_V1_REPLACEMENT ::= 2013
$URLPARSE:URL ::= $URLSPLIT:URL
$URLSPLIT:URL ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_URL_PATH
$PARSEOS:OS ::= $PARSE:OS
$PARSE:OS ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_URL_PATH ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL_PATH
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL_PATH ::= $EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_URL
$EXTRA_REQUEST_FROM_FIRST_LINE:RESULTS.REQUEST_URL ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL_PATH
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL_PATH ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL ::= $PARSE:RESULTS.REQUEST_URL_PATH
$PARSE:PARSEOS_@.FAMILY ::= $__INIT__:PARSE_@.OS.FAMILY
$PARSE:RESULTS.REQUEST_URL_PATH ::= $PARSE:VALUES.REQUEST_URL_PATH
$PARSE:VALUES.REQUEST_URL_PATH ::= $PARSE:RESULTS.REQUEST_URL
$PARSE:RESULTS.REQUEST_URL ::= $PARSE:VALUES.REQUEST_URL
$PARSE:V.OS.FAMILY ::= FreeBSD
$PARSE:VALUES.REQUEST_URL ::= /test
	| /test1
	| /test2
'''[1:-1]
    result = []
    for log in log_lines.split('\n'):
        if log.strip() == '': continue
        with induce.Tracer(log, result) as t:
            line_parser = apache_log_parser.make_parser("%h <<%P>> %t %Dus \"%r\" %>s %b  \"%{Referer}i\" \"%{User-Agent}i\" %l %u")
            log_line_data = line_parser(log)
    with induce.grammar() as g:
        for jframe in result:
            g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

