import apache_log_parser 
import induce
import collections
import random
random.seed(0)


def test_apachelogparse1():
    log_lines = '''
127.0.0.1 <<6113>> [16/Aug/2013:15:45:34 +0000] 1966093us "GET / HTTP/1.1" 200 3478  "https://example.com/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.18)" - -
'''[1:-1]
    grammar = '''
$START ::= $TEST_APACHELOGPARSE1:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.PID$ESCAPE:PATTERN[16/Aug/$USERAGENTPARSER.V1_REPLACEMENT:15:45:34 $__INIT__:STRING] $TEST_APACHELOGPARSE1:PARSE_@.TIME_US$ESCAPE:PATTERN$MATCH:STRING$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.STATUS $TEST_APACHELOGPARSE1:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"$PARSEUSERAGENT:USER_AGENT_STRING$ESCAPE:PATTERN- -
$PARSEUSERAGENT:USER_AGENT_STRING ::= $PARSEDEVICE:USER_AGENT_STRING
$__INIT__:STRING ::= $TZ_STRING
$ESCAPE:PATTERN ::=   "
	|  <<
	| " 
	| >> 
	| us "
$MATCH:STRING ::= $FIRST_LINE
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_REFERER ::= $<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER
$TEST_APACHELOGPARSE1:PARSE_@.RESPONSE_BYTES_CLF ::= $<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF
$TEST_APACHELOGPARSE1:PARSE_@.REMOTE_HOST ::= $<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST
$TEST_APACHELOGPARSE1:PARSE_@.TIME_US ::= $<LAMBDA>:MATCHED_STRINGS.TIME_US
$TEST_APACHELOGPARSE1:PARSE_@.STATUS ::= $<LAMBDA>:MATCHED_STRINGS.STATUS
$TEST_APACHELOGPARSE1:PARSE_@.PID ::= $<LAMBDA>:MATCHED_STRINGS.PID
$USERAGENTPARSER.V1_REPLACEMENT ::= $OSPARSER.OS_V1_REPLACEMENT
$PARSEDEVICE:USER_AGENT_STRING ::= Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-US; rv:1.9.2.18)
$FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE
$TZ_STRING ::= +$FIXEDOFFSET._FIXEDOFFSET__NAME
$<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER ::= $PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER
$<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF ::= $PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF
$<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST ::= $PARSE:<LAMBDA>_@.REMOTE_HOST
$<LAMBDA>:MATCHED_STRINGS.TIME_US ::= $PARSE:<LAMBDA>_@.TIME_US
$<LAMBDA>:MATCHED_STRINGS.STATUS ::= $PARSE:<LAMBDA>_@.STATUS
$<LAMBDA>:MATCHED_STRINGS.PID ::= $PARSE:<LAMBDA>_@.PID
$OSPARSER.OS_V1_REPLACEMENT ::= 2013
$PARSE_OPERATING_SYSTEM:FAMILY ::= $__NEW__:FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE
$PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER ::= $RESULTS.REQUEST_HEADER_REFERER
$PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF ::= $RESULTS.RESPONSE_BYTES_CLF
$FIXEDOFFSET._FIXEDOFFSET__NAME ::= 0000
$PARSE:<LAMBDA>_@.REMOTE_HOST ::= $RESULTS.REMOTE_HOST
$PARSE:<LAMBDA>_@.TIME_US ::= $RESULTS.TIME_US
$PARSE:<LAMBDA>_@.STATUS ::= $RESULTS.STATUS
$PARSE:<LAMBDA>_@.PID ::= $RESULTS.PID
$__NEW__:FAMILY ::= $OS
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD / HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER
$RESULTS.REQUEST_HEADER_REFERER ::= $VALUES.REQUEST_HEADER_REFERER
$RESULTS.RESPONSE_BYTES_CLF ::= $VALUES.RESPONSE_BYTES_CLF
$RESULTS.REMOTE_HOST ::= $VALUES.REMOTE_HOST
$RESULTS.TIME_US ::= $VALUES.TIME_US
$RESULTS.STATUS ::= $VALUES.STATUS
$RESULTS.PID ::= $VALUES.PID
$OS ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HTTP_VER
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD ::= $TEST_APACHELOGPARSE1:PARSE_@.REQUEST_METHOD
$VALUES.REQUEST_HEADER_REFERER ::= https://example.com/
$VALUES.RESPONSE_BYTES_CLF ::= 3478
$VALUES.REMOTE_HOST ::= 127.0.0.1
$VALUES.TIME_US ::= 1966093
$VALUES.STATUS ::= 200
$VALUES.PID ::= 6113
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_HTTP_VER ::= $RESULTS.REQUEST_HTTP_VER
$TEST_APACHELOGPARSE1:PARSE_@.REQUEST_METHOD ::= $RESULTS.REQUEST_METHOD
$PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$RESULTS.REQUEST_HTTP_VER ::= $VALUES.REQUEST_HTTP_VER
$RESULTS.REQUEST_METHOD ::= $VALUES.REQUEST_METHOD
$RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$VALUES.REQUEST_HTTP_VER ::= 1.1
$VALUES.REQUEST_METHOD ::= GET
$VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSEOS_@.FAMILY
$PARSE:PARSEOS_@.FAMILY ::= $__INIT__:PARSE_@.OS.FAMILY
$__INIT__:PARSE_@.OS.FAMILY ::= $UA_DICT.OS.FAMILY
$UA_DICT.OS.FAMILY ::= $V.OS.FAMILY
$V.OS.FAMILY ::= Linux
'''[1:-1]
    result = []
    for log in log_lines.split('\n'):
        if log.strip() == '': continue
        with induce.Tracer(log, result) as t:
            line_parser = apache_log_parser.make_parser("%h <<%P>> %t %Dus \"%r\" %>s %b  \"%{Referer}i\" \"%{User-Agent}i\" %l %u")
            log_line_data = line_parser(log)
    with induce.grammar() as g:
        for jframe in result:
                g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

def test_apachelogparse2():
    log_lines = '''
127.0.0.1 <<6113>> [16/Aug/2013:15:45:34 +0000] 1966093us "GET / HTTP/1.1" 200 3478  "https://example.com/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.18)" - -
127.0.0.1 <<6113>> [16/Aug/2013:15:45:39 +0000] 1966093us "GET /test HTTP/1.0" 200 3000  "https://myexample.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
10.1.1.1 <<6113>> [16/Aug/2013:15:35:39 +0000] 1966093us "GET /test1 HTTP/1.0" 200 3000  "https://newwebsite.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
10.1.1.1 <<6113>> [16/Aug/2013:15:45:39 +0000] 1966093us "GET /test2 HTTP/1.1" 200 3000  "https://myexample.org/" "Mozilla/5.0 (X11; U; FreeBSD x86_64; en-UK; rv:1.9.2.18)" - -
'''[1:-1]
    grammar = '''
$START ::= $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN[16/Aug/$USERAGENTPARSER.V1_REPLACEMENT:15:45:39 $__INIT__:STRING] $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD $__NEW__:PATH HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"$PARSEUSERAGENT:USER_AGENT_STRING$ESCAPE:PATTERN- -
	| $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN[16/Aug/2013:15:35:39 $__INIT__:STRING] $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD $__NEW__:PATH HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)$ESCAPE:PATTERN- -
	| $TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN[16/Aug/2013:15:45:34 $__INIT__:STRING] $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$MATCH:STRING$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-US; rv:1.9.2.18)$ESCAPE:PATTERN- -
	| 10.$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER.1$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.PID$ESCAPE:PATTERN[16/Aug/2013:15:45:39 $__INIT__:STRING] $TEST_APACHELOGPARSE2:PARSE_@.TIME_US$ESCAPE:PATTERN$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD $__NEW__:PATH HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.STATUS $TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF$ESCAPE:PATTERN$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER$ESCAPE:PATTERN"Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)$ESCAPE:PATTERN- -
$PARSE_OPERATING_SYSTEM:FAMILY ::= $__NEW__:FAMILY
$__INIT__:STRING ::= $TZ_STRING
$ESCAPE:PATTERN ::=   "
	|  <<
	| " 
	| >> 
	| us "
$MATCH:STRING ::= $FIRST_LINE
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_REFERER ::= $<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER
$TEST_APACHELOGPARSE2:PARSE_@.RESPONSE_BYTES_CLF ::= $<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF
$TEST_APACHELOGPARSE2:PARSE_@.REMOTE_HOST ::= $<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST
$TEST_APACHELOGPARSE2:PARSE_@.TIME_US ::= $<LAMBDA>:MATCHED_STRINGS.TIME_US
$TEST_APACHELOGPARSE2:PARSE_@.STATUS ::= $<LAMBDA>:MATCHED_STRINGS.STATUS
$TEST_APACHELOGPARSE2:PARSE_@.PID ::= $<LAMBDA>:MATCHED_STRINGS.PID
$__NEW__:FAMILY ::= $OS
	| $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$FIRST_LINE ::= $EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE
$TZ_STRING ::= +$FIXEDOFFSET._FIXEDOFFSET__NAME
$<LAMBDA>:MATCHED_STRINGS.REQUEST_HEADER_REFERER ::= $PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER
$<LAMBDA>:MATCHED_STRINGS.RESPONSE_BYTES_CLF ::= $PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF
$<LAMBDA>:MATCHED_STRINGS.REMOTE_HOST ::= $PARSE:<LAMBDA>_@.REMOTE_HOST
$<LAMBDA>:MATCHED_STRINGS.TIME_US ::= $PARSE:<LAMBDA>_@.TIME_US
$<LAMBDA>:MATCHED_STRINGS.STATUS ::= $PARSE:<LAMBDA>_@.STATUS
$<LAMBDA>:MATCHED_STRINGS.PID ::= $PARSE:<LAMBDA>_@.PID
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$EXTRA_REQUEST_FROM_FIRST_LINE:MATCHED_STRINGS.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE
$PARSE:<LAMBDA>_@.REQUEST_HEADER_REFERER ::= $RESULTS.REQUEST_HEADER_REFERER
$PARSE:<LAMBDA>_@.RESPONSE_BYTES_CLF ::= $RESULTS.RESPONSE_BYTES_CLF
$FIXEDOFFSET._FIXEDOFFSET__NAME ::= 0000
$PARSE:<LAMBDA>_@.REMOTE_HOST ::= $RESULTS.REMOTE_HOST
$PARSE:<LAMBDA>_@.TIME_US ::= $RESULTS.TIME_US
$PARSE:<LAMBDA>_@.STATUS ::= $RESULTS.STATUS
$PARSE:<LAMBDA>_@.PID ::= $RESULTS.PID
$PARSE:PARSE_USER_AGENT_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_FIRST_LINE ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD / HTTP/$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER
$RESULTS.REQUEST_HEADER_REFERER ::= $VALUES.REQUEST_HEADER_REFERER
$RESULTS.RESPONSE_BYTES_CLF ::= $VALUES.RESPONSE_BYTES_CLF
$RESULTS.REMOTE_HOST ::= $VALUES.REMOTE_HOST
$RESULTS.TIME_US ::= $VALUES.TIME_US
$RESULTS.STATUS ::= $VALUES.STATUS
$RESULTS.PID ::= $VALUES.PID
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_HTTP_VER ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HTTP_VER
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_METHOD ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_METHOD
$RESULTS.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$VALUES.REQUEST_HEADER_REFERER ::= https://example.com/
	| https://myexample.org/
	| https://newwebsite.org/
$VALUES.RESPONSE_BYTES_CLF ::= 3000
	| 3478
$VALUES.REMOTE_HOST ::= 10.1.1.1
	| 127.0.0.1
$VALUES.TIME_US ::= 1966093
$VALUES.STATUS ::= 200
$VALUES.PID ::= 6113
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HTTP_VER ::= $RESULTS.REQUEST_HTTP_VER
$VALUES.REQUEST_HEADER_USER_AGENT__OS__FAMILY ::= $PARSE:PARSEOS_@.FAMILY
	| $__INIT__:PARSE_@.OS.FAMILY
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_METHOD ::= $RESULTS.REQUEST_METHOD
$RESULTS.REQUEST_HTTP_VER ::= $VALUES.REQUEST_HTTP_VER
$RESULTS.REQUEST_METHOD ::= $VALUES.REQUEST_METHOD
$__INIT__:PARSE_@.OS.FAMILY ::= $UA_DICT.OS.FAMILY
$VALUES.REQUEST_HTTP_VER ::= 1.0
	| 1.1
$VALUES.REQUEST_METHOD ::= GET
$UA_DICT.OS.FAMILY ::= $CACHED.OS.FAMILY
	| $V.OS.FAMILY
$CACHED.OS.FAMILY ::= FreeBSD
	| Linux
$PARSEUSERAGENT:USER_AGENT_STRING ::= $PARSEDEVICE:USER_AGENT_STRING
$__NEW__:PATH ::= $URLPARSE:URL
$USERAGENTPARSER.V1_REPLACEMENT ::= $OSPARSER.OS_V1_REPLACEMENT
$PARSEDEVICE:USER_AGENT_STRING ::= Mozilla/5.0 (X11; U; $PARSE_OPERATING_SYSTEM:FAMILY x86_64; en-UK; rv:1.9.2.18)
$URLPARSE:URL ::= $URLSPLIT:URL
$OSPARSER.OS_V1_REPLACEMENT ::= 2013
$URLSPLIT:URL ::= $URL
$URL ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL_PATH
$OS ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_HEADER_USER_AGENT__OS__FAMILY
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL_PATH ::= $PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL
$PARSE:EXTRA_REQUEST_FROM_FIRST_LINE_@.REQUEST_URL ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL_PATH
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL_PATH ::= $TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL
$TEST_APACHELOGPARSE2:PARSE_@.REQUEST_URL ::= $RESULTS.REQUEST_URL_PATH
$RESULTS.REQUEST_URL_PATH ::= $VALUES.REQUEST_URL_PATH
$VALUES.REQUEST_URL_PATH ::= $RESULTS.REQUEST_URL
$PARSE:PARSEOS_@.FAMILY ::= $__INIT__:PARSE_@.OS.FAMILY
$RESULTS.REQUEST_URL ::= $VALUES.REQUEST_URL
$VALUES.REQUEST_URL ::= /test
	| /test1
	| /test2
$V.OS.FAMILY ::= FreeBSD
'''[1:-1]
    result = []
    for log in log_lines.split('\n'):
        if log.strip() == '': continue
        with induce.Tracer(log, result) as t:
            line_parser = apache_log_parser.make_parser("%h <<%P>> %t %Dus \"%r\" %>s %b  \"%{Referer}i\" \"%{User-Agent}i\" %l %u")
            log_line_data = line_parser(log)
    with induce.grammar() as g:
        for jframe in result:
            g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

