import urlparser
import induce
import collections
import random
random.seed(0)


def test_urlparser1():
    url_lines = '''
http://www.st.cs.uni-saarland.de/zeller#ref
'''[1:-1]
    grammar = '''
$START ::= $_PARSERESULTSWITHOFFSET.__INIT__:P1:$PARSERESULTS.__INIT__:TOKLIST$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM$_PARSERESULTSWITHOFFSET.__INIT__:P1
$_PARSERESULTSWITHOFFSET.__INIT__:P1 ::= $PARSERESULTS.__DELITEM__:VALUE
$PARSERESULTS._ASSTRINGLIST:ITEM ::= $PARSERESULTS.__NEW__:TOKLIST
$PARSERESULTS.__INIT__:TOKLIST ::= $LITERAL.__INIT__:MATCHSTRING
$PARSERESULTS.__DELITEM__:VALUE ::= $PARSERESULTS.__SETITEM__:SUB
$LITERAL.__INIT__:MATCHSTRING ::= $LITERAL._PARSENOCACHE:TOKENS
$PARSERESULTS.__NEW__:TOKLIST ::= $WORD._PARSENOCACHE:TOKENS
$LITERAL._PARSENOCACHE:TOKENS ::= $LITERAL.POSTPARSE:TOKENLIST
$PARSERESULTS.__SETITEM__:SUB ::= $PARSERESULTS.__SETITEM__:V
$WORD._PARSENOCACHE:TOKENS ::= $WORD.POSTPARSE:TOKENLIST
$LITERAL.POSTPARSE:TOKENLIST ::= $LITERAL.MATCH
$PARSERESULTS.__SETITEM__:V ::= $PARSERESULTS.__DELITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$WORD.POSTPARSE:TOKENLIST ::= $WORD._PARSENOCACHE:WORD.POSTPARSE_@
$LITERAL.MATCH ::= $LITERAL._PARSENOCACHE:LITERAL.POSTPARSE_@
$PARSERESULTS.__DELITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__GETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$WORD._PARSENOCACHE:WORD.POSTPARSE_@ ::= cs
	| de
	| st
	| uni-saarland
	| www
$PARSERESULTS.__GETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__GETATTR__:PARSERESULTS.__GETITEM___@
	| $PARSERESULTS.__SETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$LITERAL._PARSENOCACHE:LITERAL.POSTPARSE_@ ::= //
$PARSERESULTS.__SETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__IADD__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$PARSERESULTS.__GETATTR__:PARSERESULTS.__GETITEM___@ ::= $@.URLSPLIT:PARSERESULTS.__GETATTR___@
$PARSERESULTS.__IADD__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $@.<LISTCOMP>:_PARSERESULTSWITHOFFSET.__GETITEM___@
$@.URLSPLIT:PARSERESULTS.__GETATTR___@ ::= http
$@.<LISTCOMP>:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= /zeller#ref
'''[1:-1]
    result = []
    for url in url_lines.split('\n'):
        with induce.Tracer(url, result) as t:
            urlparser.urlparse(url)
    with induce.grammar() as g:
        for jframe in result:
            g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

def test_urlparser2():
    url_lines = '''
http://www.st.cs.uni-saarland.de/zeller#ref
https://www.cispa.saarland:80/bar
http://foo@google.com:8080/bar?q=r#ref2
'''[1:-1]
    grammar = '''
$START ::= $_PARSERESULTSWITHOFFSET.__INIT__:P1:$PARSERESULTS.__INIT__:TOKLIST$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM$_PARSERESULTSWITHOFFSET.__INIT__:P1?$PARSERESULTS._ASSTRINGLIST:ITEM#$PARSERESULTS._ASSTRINGLIST:ITEM
	| $_PARSERESULTSWITHOFFSET.__INIT__:P1:$PARSERESULTS.__INIT__:TOKLIST$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM.$PARSERESULTS._ASSTRINGLIST:ITEM$_PARSERESULTSWITHOFFSET.__INIT__:P1
	| http://$@.URLPARSE:NETLOC/zeller#ref
$@.URLPARSE:NETLOC ::= www.st.cs.uni-saarland.de
$_PARSERESULTSWITHOFFSET.__INIT__:P1 ::= $PARSERESULTS.__DELITEM__:VALUE
$PARSERESULTS._ASSTRINGLIST:ITEM ::= $PARSERESULTS.__NEW__:TOKLIST
$PARSERESULTS.__INIT__:TOKLIST ::= $LITERAL._PARSENOCACHE:TOKENS
$PARSERESULTS.__DELITEM__:VALUE ::= $PARSERESULTS.__SETITEM__:SUB
$LITERAL._PARSENOCACHE:TOKENS ::= $LITERAL.POSTPARSE:TOKENLIST
$PARSERESULTS.__NEW__:TOKLIST ::= $WORD._PARSENOCACHE:TOKENS
$PARSERESULTS.__SETITEM__:SUB ::= $PARSERESULTS.__SETITEM__:V
$LITERAL.POSTPARSE:TOKENLIST ::= $LITERAL.MATCH
$WORD._PARSENOCACHE:TOKENS ::= $WORD.POSTPARSE:TOKENLIST
$PARSERESULTS.__SETITEM__:V ::= $PARSERESULTS.__DELITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$WORD.POSTPARSE:TOKENLIST ::= $@.URLPARSE:FRAGMENT
	| $@.URLPARSE:QUERY
	| $WORD._PARSENOCACHE:WORD.POSTPARSE_@
$LITERAL.MATCH ::= $LITERAL._PARSENOCACHE:LITERAL.POSTPARSE_@
$PARSERESULTS.__DELITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__GETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$LITERAL._PARSENOCACHE:LITERAL.POSTPARSE_@ ::= //
$WORD._PARSENOCACHE:WORD.POSTPARSE_@ ::= cispa
	| com:8080
	| foo@google
	| saarland:80
	| www
$PARSERESULTS.__GETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__GETATTR__:PARSERESULTS.__GETITEM___@
	| $PARSERESULTS.__SETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$PARSERESULTS.__SETITEM__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $PARSERESULTS.__IADD__:_PARSERESULTSWITHOFFSET.__GETITEM___@
$PARSERESULTS.__GETATTR__:PARSERESULTS.__GETITEM___@ ::= $@.URLSPLIT:PARSERESULTS.__GETATTR___@
$PARSERESULTS.__IADD__:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= $@.<LISTCOMP>:_PARSERESULTSWITHOFFSET.__GETITEM___@
$@.URLSPLIT:PARSERESULTS.__GETATTR___@ ::= http
	| https
$@.<LISTCOMP>:_PARSERESULTSWITHOFFSET.__GETITEM___@ ::= /bar
$@.URLPARSE:FRAGMENT ::= $@.URLSPLIT:PARSERESULTS.__GETITEM___@
$@.URLPARSE:QUERY ::= $@.URLSPLIT:PARSERESULTS.__GETITEM___@
$@.URLSPLIT:PARSERESULTS.__GETITEM___@ ::= q=r
	| ref2
'''[1:-1]
    result = []
    for url in url_lines.split('\n'):
        with induce.Tracer(url, result) as t:
            urlparser.urlparse(url)
    with induce.grammar() as g:
        for jframe in result:
            g.handle_events(jframe)
        print(str(g))
        assert(grammar == str(g))

